apiVersion: v1
kind: Service
metadata:
  namespace: compage_module
  labels:
    app: compage_module
  name: compage_module
spec:
  ports:
  
    - protocol: TCP
      port: 5678
      targetPort: 5678
   
   
  selector:
    app: compage_module
  type: ClusterIP
